version: '3.8'

services:
  # Definimos nuestro primer contenedor (servicio)
  app:
    build: .
    container_name: prueba-tecnica-app
    ports:
      - "8080:8080"
    env_file:
      - .env # para la seguridad